# Jenkins runs pipelines on the host system that it is setup on. To run it on windows
# install the server on a windows machine by following https://www.jenkins.io/doc/book/installing/windows/
# once it has been setup add the below step to your pipeline file to run automated tests using Postman CLI.

pipeline {
  agent any

  tools {nodejs "{your_nodejs_configured_tool_name}"}

  stages {
    stage('Install Postman CLI') {
      steps {
        sh 'powershell.exe -NoProfile -InputFormat None -ExecutionPolicy AllSigned -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"'
      }
    }

    stage('Postman CLI Login') {
      steps {
        sh 'postman login --with-api-key $POSTMAN_API_KEY'
      }
    }

    stage('Running collection') {
      steps {
        sh 'postman collection run "38912412-3e6dc11e-5444-48b9-b478-f6c258b9c213" -e "38912412-9afce138-4eb6-4ba4-a7d9-20f5d82470c9"'
      }
    }
  }
}
